# Generated by Django 4.2.5 on 2023-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Join',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Phone_Number',
            field=models.IntegerField(null=True),
        ),
    ]
